export const FETCH_STATISTICS = 'http://localhost:3001/statistics';
export const FETCH_COUNTRIES = 'https://covid-193.p.rapidapi.com/countries';
export const GET_ALL_STATISTICS = 'GET_ALL_STATISTICS';
export const GET_ALL_STATISTICS_PENDING = 'GET_ALL_STATISTICS_PENDING';
export const GET_ALL_STATISTICS_FULFILLED = 'GET_ALL_STATISTICS_FULFILLED';
export const GET_ALL_STATISTICS_REJECTED = 'GET_ALL_STATISTICS_REJECTED';
export const CHANGE_INPUT_STRING = 'CHANGE_INPUT_STRING';
export const GET_COUNTRY_STATISTICS = 'GET_COUNTRY_STATISTICS';
export const GET_COUNTRY_STATISTICS_PENDING = 'GET_COUNTRY_STATISTICS_PENDING';
export const GET_COUNTRY_STATISTICS_FULFILLED = 'GET_COUNTRY_STATISTICS_FULFILLED';
export const GET_COUNTRY_STATISTICS_REJECTED = 'GET_COUNTRY_STATISTICS_REJECTED';


